config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => "custom_devise/registrations",
    :passwords => "custom_devise/passwords"
  }

  root to: "pages#landing"

  get "faq" => "pages#faq", as: :faq
  get "partners" => "pages#partners", as: :partners
  get "copyright-and-trademark" => "pages#copyright_and_trademark", as: :copyright_and_trademark
  get "disclaimer" => "pages#disclaimer", as: :disclaimer
  get "privacy-policy" => "pages#privacy_policy", as: :privacy_policy
  get "service-agreement" => "pages#service_agreement", as: :service_agreement

  scope "experts" do
    get "/" => "experts#index", as: :experts
    get "book/:expert_id" => "experts#book", as: :book_expert
  end

  resources :users, only: [:show, :update]
  resources :calls, only: [:create, :update, :index] do
    member do
      post :accept
      post :rate
      get  :rate_with_rating
      post :cancel
      post :start
    end
    collection do
      get :upcoming
      get :alipay_callback
    end
  end
  resources :promotions, only: [:index] do
    collection do
      post :check
    end
  end
  resources :partnership_requests, only: [:create]

  namespace :webhooks do
    scope "cloopen" do
      post :joined_conference
      post :conference_ended
    end
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController

  before_action :auto_login, except: [:create]
  before_action :check_for_admin, only: [:upcoming, :start]

  def create
    if current_user
      @user = current_user
    else
      @user = User.new(user_params)
      if !@user.save
        flash[:alert] = @user.errors.full_messages.join("，") + "。"
        return redirect_to book_expert_path(params[:call][:expert_id])
      else
        sign_in(:user, @user)
      end
    end

    @expert = User.find(params[:call][:expert_id])
    amount_to_charge = @expert.rate_in_cents_for(params[:call][:est_duration_in_min].to_i)

    merge_dates
    @call = Call.new(call_params)
    @call.user = @user
    @call.user_accepted_at = Time.current

    if @call.save

      if !@user.has_free_calls_remaining_to_complete?

        alipay = Alipay::Pay.new(@call, amount_to_charge, alipay_callback_calls_url, device_is_mobile?)
        alipay_url = alipay.run!

        return redirect_to alipay_url
      end

      redirect_to calls_path
    else
      flash[:alert] = @calls.errors.full_messages.join("，") + "。"
      redirect_to experts_path
    end
  end

  def alipay_callback
    success = params[:is_success] == "T"
    call = Call.find(params[:out_trade_no])
    expert = call.expert
    if success
      amount = params[:total_fee].to_f
      trade_no = params[:trade_no]
      
      Payment.make(current_user, call, amount, trade_no)

      flash[:notice] = "<strong>#{current_user.name}</strong>，感谢你的通话申请！我们正在努力为你安排与<strong>#{expert.name}</strong>直接通话。通话申请确认邮件已发送到你登记的电子邮箱，请查阅详情。你也可以在个人主页查看你的通话申请。"
      send_confirmation_emails(current_user, call.expert, call)
      return redirect_to calls_path
    else
      call.delete
      flash[:alert] = "不好意思，您付款出了问题，请再次申请通话。"
      return redirect_to book_expert_path(expert.id)
    end
  end

  def index
    if params[:acceptor].present?
      @call = Call.find(params[:call_id])
      accept_call(@call)
    end
    @completed_calls = current_user.all_completed_calls
    @in_progress_calls = current_user.all_calls - @completed_calls
    @cancelled_calls = current_user.all_cancelled_calls
    @available_times = default_available_times
    @today = Time.current
  end

  def accept
    @call = Call.find(params[:id])
    accept_call(@call) unless @call.accepted?
    redirect_to calls_path
  end

  def update
    @call = Call.find(params[:id])
    merge_dates if datetimes_passed_in
    @call.assign_attributes(call_params)
    new_time_offered = datetimes_changed(@call)
    @call = @call.change_user_or_expert_accepted_at(current_user) if datetimes_changed(@call)
    if @call.save
      send_edit_call_email(@call) if new_time_offered
      flash[:notice] = "成功更改与#{@call.other_user(current_user).name}的通话申请"
    else
      flash[:alert] = @call.errors.full_messages.join("，") + "。"
    end
    redirect_to calls_path
  end

  def rate
    @call = Call.find(params[:id])
    @call.assign_attributes(call_params)
    if current_user.is_user_in?(@call) && @call.user_review.present?
      @call.user_review_left_at = Time.current
    elsif current_user.is_expert_in?(@call) && @call.expert_review.present?
      @call.expert_review_left_at = Time.current
    end

    if @call.save
      flash[:notice] = "感谢你给#{@call.expert.name}留了评论"
    else
      flash[:alert] = @call.errors.full_messages.join("，") + "。"
    end
    redirect_to calls_path(t: "completed")
  end

  def rate_with_rating
    @call = Call.find(params[:id])
    if current_user.is_user_in?(@call)
      @call.update_attributes(user_rating: params[:r])
      flash[:notice] = "感谢你给#{@call.expert.name}留了评论"
    elsif current_user.is_expert_in?(@call)
      @call.update_attributes(expert_rating: params[:r])
      flash[:notice] = "感谢你给#{@call.user.name}留了评论"
    end
    redirect_to calls_path(t: "completed", openRating: @call.id)
  end

  def cancel
    @call = Call.find(params[:id])
    @call.assign_attributes(call_params)
    @call.cancelled_at = Time.current
    @call.user_that_cancelled = current_user

    if !@call.free
      if @call.accepted? && @call.cancelled_by_user? && @call.apply_cancellation_fee?
        if @call.need_to_pay_after_cancellation?
          customer = StripeTask.customer(@call.user)
          charge = StripeTask.charge(customer, @call.payment_amount_for_early_cancellation, "与#{@call.expert.name}通话提早取消")
          Payment.make(@call.user, @call, charge)

          # TODO: Error handling for failed charges
          
        elsif @call.need_to_refund_after_cancellation?
          customer = StripeTask.customer(@call.user)
          Refund.refund_call(@call, @call.refund_amount_for_early_cancellation, @call.cancellation_fee_in_cents, customer)
        end
      elsif @call.has_positive_paid_balance?
        customer = StripeTask.customer(@call.user)
        Refund.refund_call(@call, @call.net_paid, 0, customer)
      end
    end

    # TODO: Account for situation where someone used promo code to sign up, and then cancel
    # We should be giving that credit back to the customer

    if @call.save
      send_cancellation_emails(@call)
      flash[:notice] = "取消了你与#{@call.cancellee.name}的通话"
    else
      flash[:alert] = @call.errors.full_messages.join("，") + "。"
    end
    redirect_to calls_path(t: "cancelled")
  end

  def upcoming
    @future_confirmed_calls = Call.confirmed.future.order(:scheduled_at)
  end

  def start
    call = Call.find(params[:id])
    conference_cloopen = Cloopen::Conference.new
    conference_response = conference_cloopen.create_conference
    call.update_details_from_cloopen(conference_response)
    call.started_at = Time.current
    call.save

    sms_cloopen = Cloopen::Sms.new
    sms_cloopen.call_starting_reminder(call.user.phone, call.expert.name, call) if call.user.phone.present?
    sms_cloopen.call_starting_reminder(call.expert.phone, call.user.name, call) if call.expert.phone.present?
    redirect_to upcoming_calls_path
  end

  protected

  def call_params
    params.require(:call).permit(
      :description,
      :est_duration_in_min,
      :user_id,
      :expert_id,
      :user_rating,
      :expert_rating,
      :user_review,
      :expert_review,
      :offer_time_one,
      :offer_time_two,
      :offer_time_three,
      :scheduled_at,
      :user_accepted_at,
      :expert_accepted_at,
      :cancellation_reason,
      :free
    )
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :phone,
      :password,
      :agreed_to_policies
    )
  end

  def merge_dates
    params[:call][:offer_time_one] = parse_text_into_date("#{params[:call][:offer_time_one_date]} #{params[:call][:offer_time_one_hour]}:00")
    params[:call][:offer_time_two] = parse_text_into_date("#{params[:call][:offer_time_two_date]} #{params[:call][:offer_time_two_hour]}:00")
    params[:call][:offer_time_three] = parse_text_into_date("#{params[:call][:offer_time_three_date]} #{params[:call][:offer_time_three_hour]}:00")
  end

  def send_confirmation_emails(user, expert, call)
    user_data = expert_data = {
      user: user,
      expert: expert,
      call: call,
      link_to_manage_calls: email_link_for_calls(user)
    }
    expert_data[:link_to_manage_calls] = email_link_for_calls(expert)
    expert_data[:link_to_accept_call_one] = email_link_for_accepting_calls(expert, call, 1, Call::EXPERT_ACCEPTOR_TEXT)
    expert_data[:link_to_accept_call_two] = email_link_for_accepting_calls(expert, call, 2, Call::EXPERT_ACCEPTOR_TEXT)
    expert_data[:link_to_accept_call_three] = email_link_for_accepting_calls(expert, call, 3, Call::EXPERT_ACCEPTOR_TEXT)

    Emails::Call.send_confirmation_of_call_request_to_user(user_data)
    Emails::Call.send_initial_request_to_expert(expert_data)
    Emails::Call.send_request_notification_to_admin(user_data, rails_admin_path(call), general_email)
  end

  def send_edit_call_email(call)
    receiver = call.other_user(current_user)
    role = receiver.role_in(call)
    data = {
      call: call,
      receiver: receiver,
      editing_user: current_user,
      link_to_manage_calls: email_link_for_calls(receiver),
      link_to_accept_call_one: email_link_for_accepting_calls(receiver, call, 1, role),
      link_to_accept_call_two: email_link_for_accepting_calls(receiver, call, 2, role),
      link_to_accept_call_three: email_link_for_accepting_calls(receiver, call, 3, role)
    }
    Emails::Call.edit_request(data)
  end

  def accept_call(call)
    if params[:acceptor] == Call::EXPERT_ACCEPTOR_TEXT && call.expert == current_user
      call.accept_as_expert(params[:datetime_num].to_i)
      flash[:notice] = "感谢你接受在<strong>#{ChineseTime.display(call.scheduled_at)}</strong>与<strong>#{call.user.name}</strong>通话"
    elsif params[:acceptor] == Call::USER_ACCEPTOR_TEXT && call.user == current_user
      call.accept_as_user(params[:datetime_num].to_i)
      flash[:notice] = "接受成功：<strong>#{ChineseTime.display(call.scheduled_at)}</strong>与<strong>#{call.expert.name}</strong>通话"
    end
    call.set_initial_conference_details
    call.save
    send_confirmation_of_calls_emails(call)
  end

  def send_confirmation_of_calls_emails(call)
    Emails::Call.send_call_acceptance_confirmation(call, email_link_for_calls(call.user), Call::USER_ACCEPTOR_TEXT)
    Emails::Call.send_call_acceptance_confirmation(call, email_link_for_calls(call.expert), Call::EXPERT_ACCEPTOR_TEXT)
    Emails::Call.send_call_acceptance_confirmation_to_admin(call, rails_admin_path(call), general_email)
  end

  def send_cancellation_emails(call)
    Emails::Call.send_cancel_notice(call, email_link_for_calls(call.cancellee))
    Emails::Call.send_cancellation_notice_to_admin(call, rails_admin_path(call), general_email)
  end

  def datetimes_passed_in
    params[:call][:offer_time_one_date].present? &&
    params[:call][:offer_time_two_date].present? &&
    params[:call][:offer_time_three_date].present?
  end

  def datetimes_changed(call)

app/helpers/calls_helper.rb
module CallsHelper
  def callout_class(call)
    case call.status
    when Call::PENDING_EXPERT_ACCEPTANCE
      "secondary"
    when Call::PENDING_USER_ACCEPTANCE
      "warning"
    when Call::MUTUALLY_ACCEPTED
      "success"
    end
  end

  def link_to_accept(call, datetime_num)
    str = " - "
    str += link_to "接受", accept_call_path(call, acceptor: current_user.role_in(call), datetime_num: datetime_num), method: :post
  end
end

app/views/calls/_cancel_call_modal.html.slim
.reveal.tiny.modal-slide id="cancelCallModal#{call.id}" data-reveal="" data-close-on-click="true"
  h3
    - cancel_target = call.expert == current_user ? call.user : call.expert
    = "取消跟<strong>#{cancel_target.name}</strong>的通话".html_safe
  
  = simple_form_for call, url: cancel_call_path(call), method: "post" do |f|
    - if call.would_be_charged_cancellation_fee?
      h5.alert-text
        = "请注意：因为你未能在预定通话时间前#{Call::CANCELLATION_BUFFER_IN_HOURS_BEFORE_CALL_IS_CHARGED}小时取消通话，所以我们将收取该专家#{Call::MINUTES_TO_CHARGE_FOR_CANCELLATION}分钟(¥#{call.pure_cancellation_fee})的通话费用。"
        small
          / TODO: Link to FAQ
          = link_to "我开窍会收额外的费用吗？", ""

    = f.input :cancellation_reason, label: "取消原因", required: false
    = f.submit "取消通话", class: "button alert"

  button.close-button data-close="" aria-label="Close reveal" type="button"
    span aria-hidden="true"
      | &times;

app/views/calls/_comments_from_users_modal.html.slim
.reveal.modal-slide.comments-from-users-modal id="commentsFromUsers#{expert.id}" data-reveal="" data-close-on-click="true"
  h3
    = "点评：<strong>#{expert.name}</strong>".html_safe
  
  hr

  - if expert.use_fake_comments
    - expert.fake_comments.each do |fake_comment|
      = render "calls/fake_comment", fake_comment: fake_comment
      
  - calls_with_user_reviews.each do |call|
    = render "calls/review_list", call: call

  button.close-button data-close="" aria-label="Close reveal" type="button"
    span aria-hidden="true"
      | &times;

app/views/calls/_datetime_picker.html.slim
- call ||= nil

.datetime-picker-holder ng-controller="DatetimePickerCtrl"
  .row.date-pickers
    .small-12.large-6.columns
      .input-group
        span.input-group-label
          | 日期：
        input.datepicker type="text" value="#{call ? call.offer_time_one.strftime('%Y-%m-%d') : today}" name="call[offer_time_one_date]"

    .small-12.large-6.columns
      .input-group
        span.input-group-label
          | 时间：
        - default_index = 3
        - index = call ? available_times.index([ChineseTime.display_time_only(call.offer_time_one), call.offer_time_one.strftime("%-H:%M")]) : default_index
        = select_tag "call[offer_time_one_hour]", options_for_select(available_times, available_times[index || default_index])

  .row.date-pickers
    .small-12.large-6.columns
      .input-group
        span.input-group-label
          | 日期：
        input.datepicker type="text" value="#{call ? call.offer_time_two.strftime('%Y-%m-%d') : today}" name="call[offer_time_two_date]"

    .small-12.large-6.columns
      .input-group
        span.input-group-label
          | 时间：
        - default_index = 4
        - index = call ? available_times.index([ChineseTime.display_time_only(call.offer_time_two), call.offer_time_two.strftime("%-H:%M")]) : default_index
        = select_tag "call[offer_time_two_hour]", options_for_select(available_times, available_times[index || default_index])

  .row.date-pickers
    .small-12.large-6.columns
      .input-group
        span.input-group-label
          | 日期：
        input.datepicker type="text" value="#{call ? call.offer_time_three.strftime('%Y-%m-%d') : today}" name="call[offer_time_three_date]"

    .small-12.large-6.columns
      .input-group
        span.input-group-label
          | 时间：
        - default_index = 5
        - index = call ? available_times.index([ChineseTime.display_time_only(call.offer_time_three), call.offer_time_three.strftime("%-H:%M")]) : default_index
        = select_tag "call[offer_time_three_hour]", options_for_select(available_times, available_times[index || default_index])

app/views/calls/_edit_call_modal.html.slim
.reveal.small.modal-slide id="editCallModal#{call.id}" data-reveal="" data-close-on-click="true"
  h3
    - edit_target = call.other_user(current_user)
    = "更改与<strong>#{edit_target.name}</strong>的通话".html_safe
  
  = simple_form_for call, url: call_path(call), method: "put" do |f|
    - if call.user == current_user
      h6
        b
          | 通话内容简介：
      = f.input :description, label: false, input_html: {rows: 5}
    = render "datetime_picker", today: @today, available_times: @available_times, call: call if call.person_to_action == current_user
    = f.submit "更改通话", class: "button secondary"

  button.close-button data-close="" aria-label="Close reveal" type="button"
    span aria-hidden="true"
      | &times;

app/views/calls/_fake_comment.html.slim
.review-list-holder
  .left-side
    div
      - if fake_comment.profile_pic_url.present?
        = image_tag fake_comment.profile_pic_url, class: "profile-circle small"
      - else
        = image_tag "https://s3-us-west-2.amazonaws.com/wokaiqiao/users/missing-user.png", class: "profile-circle small"
    div
      = fake_comment.name
  .right-side
    .triangle-isosceles.left
      = simple_format fake_comment.review
    .review-details-holder
      = ChineseTime.display(fake_comment.reviewed_at, true)

app/views/calls/_list.html.slim
.call-list-holder id="#{call.anchor_tag}"
  .row
    .small-12.column
      - if expert == current_user
        .user-as-call-expert-indicator-holder
          span.user-as-call-expert-indicator
            | 你是这个通话的专家
      .row
        .small-12.medium-2.column.profile-circle-holder
          img.profile-circle src="#{other_user.picture.url(:medium)}"
          h4.call-name
            b
              = other_user.name
          
          = render "experts/read_only_expert_rating", expert: expert if other_user == expert

          hr.show-for-small-only

        .small-12.medium-6.columns
          h5.call-title
            b
              = other_user.title

          .subtitle-holder
            h6
              small.subtitle
                i.fa.fa-graduation-cap
                - education_text = other_user.educations.any? ? other_user.list_education : "未填写"
                = " #{education_text}"

            h6
              small.subtitle
                i.fa.fa-map-pin
                = " #{other_user.location || '未填写'}"

            .call-details-holder
              div
                .left-side
                  .inline-title
                    | 现在就职：
                .right-side
                  = other_user.current_work || "未填写"

              div
                .left-side
                  .inline-title
                    | 曾经就职：
                .right-side
                  = other_user.past_work || "未填写"
                
              div
                .left-side
                  .inline-title
                    | 专长领域：
                .right-side
                  = other_user.description || "未填写"

              div
                .left-side
                  .inline-title
                    | 交谈语言：
                .right-side
                  = other_user.languages || "未填写"

        .small-12.medium-4.column.end
          .callout.action-callout class="#{callout_class(call)}"
            = render "calls/action_callout/main", call: call, expert: expert

      - unless (i + 1) == max
        br
        hr
        br
        
  = render "edit_call_modal", call: call
  = render "cancel_call_modal", call: call
  = render "rate_call_modal", call: call

app/views/calls/_rate_call_modal.html.slim
.reveal.tiny.modal-slide.ratable id="rateCallModal#{call.id}" data-reveal="" data-close-on-click="true" ng-controller="RatingsCtrl"
  h3
    - rating_target = call.expert == current_user ? call.user : call.expert
    = "给<strong>#{rating_target.name}</strong>留个点评".html_safe
  
  = simple_form_for call, url: rate_call_path(call), method: "post" do |f|

    - if current_user == call.user

      label
        | 几颗星？
      .blank-raty-div.blank-user-raty-div data-user-rating="#{call.user_rating}"

      = f.input :user_review, label: "评论", required: false
      
    - else

      label
        | 几颗星？
      .blank-raty-div.blank-expert-raty-div data-expert-rating="#{call.expert_rating}"

      = f.input :expert_review, label: "评论", required: false

    h5.alert-text.hide
      | 请留几颗星的评论

    = f.submit "点评", class: "button primary leave-rating-button"

  button.close-button data-close="" aria-label="Close reveal" type="button"
    span aria-hidden="true"
      | &times;

app/views/calls/_review_list.html.slim
- reviewer = call.user
.review-list-holder
  .left-side
    div
      = image_tag reviewer.picture.url(:thumb), class: "profile-circle small"
    div
      = reviewer.name
  .right-side
    .triangle-isosceles.left
      = simple_format call.user_review
    .review-details-holder
      - if reviewer.is_user_in?(call)
        = ChineseTime.display(call.user_review_left_at, true)
      - else
        = ChineseTime.display(call.expert_review_left_at, true)

app/views/calls/index.html.slim
.all-calls-holder ng-controller="CallListCtrl"
  .page-banner-holder
    .row
      .small-12.columns
        h3
          | 管理申请

  .row
    .small-12.large-10.large-offset-1.columns
      ul#calls-tabs.tabs data-tabs=""
        li.tabs-title.is-active
          a.calls-tab-title href="#in-progress" aria-selected="true"
            | 进行中
        li.tabs-title
          a.calls-tab-title href="#completed"
            | 已完成
        li.tabs-title
          a.calls-tab-title href="#cancelled"
            | 已取消

      .tabs-content data-tabs-content="calls-tabs"
        #in-progress.tabs-panel.is-active
          br
          - if @in_progress_calls.any?
            - @in_progress_calls.each_with_index do |call, i|
              - other_user = call.other_user(current_user)
              = render "list", call: call, expert: call.expert, i: i, max: @in_progress_calls.length, other_user: other_user

          - else
            | 您目前没有在进行中的通话。

        #completed.tabs-panel
          br
          - if @completed_calls.any?
            - @completed_calls.each_with_index do |call, i|
              - other_user = call.other_user(current_user)
              = render "list", call: call, expert: call.expert, i: i, max: @completed_calls.length, other_user: other_user

          - else
            | 您目前还没有完成任何通话。

        #cancelled.tabs-panel
          br
          - if @cancelled_calls.any?
            - @cancelled_calls.each_with_index do |call, i|
              - other_user = call.other_user(current_user)
              = render "list", call: call, expert: call.expert, i: i, max: @cancelled_calls.length, other_user: other_user

          - else
            | 您目前还没有取消任何通话。

app/views/calls/upcoming.html.slim
.page-banner-holder
  .row
    .small-12.columns
      h3
        | Upcoming calls

.upcoming-calls-holder
  .row
    .small-12.columns
      table
        thead
          tr
            th
              | ID
            th
              | User
            th
              | Expert
            th
              | Scheduled at
            th
              | Actions
            th
              | Cloopen conf ID

        tbody
          - @future_confirmed_calls.each do |call|
            tr
              td
                = link_to call.id, rails_admin_link(call), target: "_blank"
              td
                = link_to call.user.name, rails_admin_link(call.user), target: "_blank"
              td
                = link_to call.expert.name, rails_admin_link(call.expert), target: "_blank"
              td
                = ChineseTime.display(call.scheduled_at, true)
              td
                - if call.started?
                  = "Started at #{ChineseTime.display(call.started_at, true)}"
                - else
                  = link_to "Start call", start_call_path(call), method: :post, class: "button start-call-button"
              td
                = call.conference_call_participant_code