config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => "custom_devise/registrations",
    :passwords => "custom_devise/passwords"
  }

  root to: "pages#landing"

  get "faq" => "pages#faq", as: :faq
  get "partners" => "pages#partners", as: :partners
  get "copyright-and-trademark" => "pages#copyright_and_trademark", as: :copyright_and_trademark
  get "disclaimer" => "pages#disclaimer", as: :disclaimer
  get "privacy-policy" => "pages#privacy_policy", as: :privacy_policy
  get "service-agreement" => "pages#service_agreement", as: :service_agreement

  scope "experts" do
    get "/" => "experts#index", as: :experts
    get "book/:expert_id" => "experts#book", as: :book_expert
  end

  resources :users, only: [:show, :update]
  resources :calls, only: [:create, :update, :index] do
    member do
      post :accept
      post :rate
      get  :rate_with_rating
      post :cancel
      post :start
    end
    collection do
      get :upcoming
      get :alipay_callback
    end
  end
  resources :promotions, only: [:index] do
    collection do
      post :check
    end
  end
  resources :partnership_requests, only: [:create]

  namespace :webhooks do
    scope "cloopen" do
      post :joined_conference
      post :conference_ended
    end
  end
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  has_many :credits
  has_and_belongs_to_many :users, uniq: true

  validates :name,
            :code,
            :amount_in_cents,
            :currency,
            :free_call_count,
            :redemption_limit,
            presence: true
  validate :cannot_redeem_past_limit

  scope :has_free_calls, -> {
    where("free_call_count > ?", 0)
  }

  before_save :upcase_code

  def amount
    amount_in_cents / 100
  end

  def has_credits?
    amount_in_cents.present? && amount_in_cents > 0
  end

  def has_free_calls?
    free_call_count.present? && free_call_count > 0
  end

  private

  def upcase_code
    self.code.upcase!
  end

  def cannot_redeem_past_limit
    promo = Promotion.find_by_code(code)
    if promo.present? && promo.users.count > promo.redemption_limit
      errors.add(:redemption_limit, "已经达到了")
    end
  end

end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @credits = current_user.credits.order(:created_at)
    @free_call_promotions = current_user.promotions.has_free_calls
  end

  def check
    promotion = Promotion.find_by_code(params[:code].upcase)
    if promotion.present? && current_user.promotions.where(id: promotion.id).any?
      flash[:alert] = "你已经加过了这个代码：#{params[:code]}"
    elsif promotion.present?
      flash[:notice] = "成功激活折扣代码："
      promo_details = []

      if promotion.has_credits?
        Credit.create_for(current_user, promotion)
        promo_details << "增加¥#{promotion.amount}金额"
      end

      if promotion.has_free_calls?
        promo_details << "增加#{promotion.free_call_count}个免费通话"
      end

      current_user.promotions << promotion
      flash[:notice] += promo_details.join("，")
    elsif params[:code].blank?
      flash[:alert] = "请输入代码"
    else
      flash[:alert] = "没有这个代码：#{params[:code]}"
    end
    redirect_to promotions_path
  end

end

app/views/promotions/index.html.slim
.page-banner-holder
  .row
    .small-12.columns
      h3
        | 折扣代码

.promotions-page-holder
  .row
    .small-12.medium-6.medium-offset-3.large-4.large-offset-4.columns

      h5
        b
          | 如果你在我们的活动中收到折扣代码，请在下面输入：

      = simple_form_for Promotion.new, url: check_promotions_path, method: "post" do |p|
        .input-group
          span.input-group-label
            | 请输入代码
          input.input-group-field type="text" name="code" style="text-transform: uppercase;"
          .input-group-button
            input.button type="submit" value="确认"

      br

    .small-12.columns

      - if @credits.any?

        table
          thead
            tr
              th
                | 详细
              th.hide-for-small-only
                | 代码
              th.hide-for-small-only
                | 使用日期
              th.right-align
                | 金额

          tbody
            - @credits.each do |credit|
              tr
                td
                  - if credit.is_earned?
                    = credit.promotion.try(:name)
                  - elsif credit.is_used?
                    - tab = credit.call.completed? ? "completed" : "in-progress"
                    = link_to "与#{credit.call.expert.name}通话", calls_path(t: tab, anchor: credit.call.anchor_tag)
                td.hide-for-small-only
                  - if credit.is_earned?
                    = credit.promotion.try(:code)
                  - else
                    | -
                td.hide-for-small-only
                  = ChineseTime.display(credit.created_at)
                td.right-align
                  = number_to_currency(credit.amount, unit: "¥", precision: 0)

            tr
              td
              td.hide-for-small-only
              td.hide-for-small-only
              td.right-align
                b
                  = "折扣余额：#{number_to_currency(current_user.net_credits, unit: "¥", precision: 0)}"

      - if @free_call_promotions.any?

        table
          thead
            tr
              th
                | 详细
              th.hide-for-small-only
                | 代码
              th.right-align
                | 几通免费电话

          tbody
            - @free_call_promotions.each do |promo|
              tr
                td
                  = promo.name
                td.hide-for-small-only
                  = promo.code
                td.right-align
                  = promo.free_call_count
            tr
              td
              td.hide-for-small-only
              td.right-align
                b
                  = "总共：#{current_user.free_calls_available}通免费通话"

        p
          = "你已经使用了#{current_user.free_calls_completed}通免费通话。"
        p
          = "你还有#{current_user.free_calls_remaining_to_complete}通免费通话。"