config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
    :registrations => "custom_devise/registrations",
    :passwords => "custom_devise/passwords"
  }

  root to: "pages#landing"

  get "faq" => "pages#faq", as: :faq
  get "partners" => "pages#partners", as: :partners
  get "copyright-and-trademark" => "pages#copyright_and_trademark", as: :copyright_and_trademark
  get "disclaimer" => "pages#disclaimer", as: :disclaimer
  get "privacy-policy" => "pages#privacy_policy", as: :privacy_policy
  get "service-agreement" => "pages#service_agreement", as: :service_agreement

  scope "experts" do
    get "/" => "experts#index", as: :experts
    get "book/:expert_id" => "experts#book", as: :book_expert
  end

  resources :users, only: [:show, :update]
  resources :calls, only: [:create, :update, :index] do
    member do
      post :accept
      post :rate
      get  :rate_with_rating
      post :cancel
      post :start
    end
    collection do
      get :upcoming
      get :alipay_callback
    end
  end
  resources :promotions, only: [:index] do
    collection do
      post :check
    end
  end
  resources :partnership_requests, only: [:create]

  namespace :webhooks do
    scope "cloopen" do
      post :joined_conference
      post :conference_ended
    end
  end
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  def index
    @tags = Tag.all

    if params[:t].present?

      if params[:s] == User::PRICE_UP
        @experts = Tag.find(params[:t]).experts.order("rate_per_minute ASC, id ASC").page(params[:page])
      elsif params[:s] == User::PRICE_DOWN
        @experts = Tag.find(params[:t]).experts.order("rate_per_minute DESC, id ASC").page(params[:page])
      elsif params[:s] == User::HIGHEST_RATING
        sorted_experts = Tag.find(params[:t]).experts.sort_by(&:avg_rating_as_expert).reverse
        @experts = Kaminari.paginate_array(sorted_experts).page(params[:page]).per(10)
      elsif params[:s] == User::MOST_COMMENTS
        sorted_experts = Tag.find(params[:t]).experts.sort_by(&:num_comments_from_users).reverse
        @experts = Kaminari.paginate_array(sorted_experts).page(params[:page]).per(10)
      else # Default to sort by domestic
        @experts = Tag.find(params[:t]).experts.order("domestic DESC, id ASC").page(params[:page])
      end

    else

      if params[:s] == User::PRICE_UP
        @experts = User.experts.order("rate_per_minute ASC, id ASC").page(params[:page])
      elsif params[:s] == User::PRICE_DOWN
        @experts = User.experts.order("rate_per_minute DESC, id ASC").page(params[:page])
      elsif params[:s] == User::HIGHEST_RATING
        sorted_experts = User.experts.sort_by(&:avg_rating_as_expert).reverse
        @experts = Kaminari.paginate_array(sorted_experts).page(params[:page]).per(10)
      elsif params[:s] == User::MOST_COMMENTS
        sorted_experts = User.experts.sort_by(&:num_comments_from_users).reverse
        @experts = Kaminari.paginate_array(sorted_experts).page(params[:page]).per(10)
      else # Default to sort by domestic
        @experts = User.experts.order("domestic DESC, id ASC").page(params[:page])
      end

    end
  end

  def book
    @call = Call.new
    @expert = User.find(params[:expert_id])
    if current_user && current_user == @expert
      flash[:alert] = "你不能与自己通话..."
      return redirect_to request.referrer || root_path
    end
    estimated_durations = [15, 30, 60]
    @estimated_call_durations = []
    estimated_durations.each do |duration|
      @estimated_call_durations << ["#{duration}分钟 (¥#{@expert.rate_for(duration)})", duration]
    end
    @user = User.new if current_user.nil?

    @available_times = default_available_times
    @today = Time.current
  end
end

app/views/experts/_book_section_four.html.slim
.small-12.medium-8.columns.end
  div
    .left-side
      .numbered-circle
        | 4
    .right-side
      h5
        | 注册

  br

  .row
    .small-12.medium-8.columns.end
      p
        = "已经注册了？#{link_to '请快速登入', new_user_session_path}".html_safe
      = render "devise/registrations/registration_fields", resource: user, resource_name: :user, just_fields: true
      = f.submit "立即申请通话", class: "button"

app/views/experts/_book_section_one.html.slim
.small-12.columns
  div
    .left-side
      .numbered-circle
        | 1
    .right-side
      h5
        | 电话会议申请资料

br

.small-12.columns
  div.description-holder
    .input-group
      span.input-group-label
        | 通话内容简介：
      = f.input :description, placeholder: "想与专家查询的事情", type: "number", label: false

.small-12.columns.end
  div.est-duration-holder
    .input-group
      span.input-group-label
        | 预计通话长度：
      = select_tag "call[est_duration_in_min]", options_for_select(@estimated_call_durations, @estimated_call_durations.first)

.small-8.columns.end
  .disclaimer-text
    p
      | 预计通话长度不会影响通话收费，但可能影响专家安排通话的时间。通话结束后按实际通话长度收费。请查阅使用我开窍的礼仪。你会收到关于通话最新消息的电邮，你也可以到你的个人主页获得同样信息。

app/views/experts/_book_section_three.html.slim
br
.small-12.columns
  div
    .left-side
      .numbered-circle
        | 3
    .right-side
      h5
        | 请注意

  br

  .row
    .small-12.columns
      p
        b
          | 同校校友优惠
      p
        = "我开窍支持及鼓励校友之间的资讯共享、互利互惠，因此与同校校友的通话费用全额免费。如果你没收到我们的学校验证电邮，请尽快与我们联系 – #{mail_to 'contact@wokaiqiao.com'}。此优惠仅限用于验证成功以后的同校校友通话。验证成功之前所支付的通话服务费用不可退返。".html_safe

      p
        b
          | 迟到政策
   
      p
        = "如果你迟到十分钟及其以上或者没有赴约，专家可选择继续提供通话服务。如果专家拒绝继续通话，你必须支付#{Call::MINUTES_TO_CHARGE_FOR_CANCELLATION}分钟的通话费用；如果专家愿意继续通话，则按通话长度收费。"
      p
        | 罚金不适用于经验证的同校校友。
   
      p
        b
          | 取消政策
      p
        | 如果需要临时更改或取消通话申请，请尽早与专家联系，以方便专家安排工作行程或将通话时段分配给其他有需要的用户。
      p
        = "请注意如果你在约定的通话时间前2小时取消通话，将不会有任何收费，否则我们会收取该专家#{Call::MINUTES_TO_CHARGE_FOR_CANCELLATION}分钟的通话费用。".html_safe

app/views/experts/_book_section_two.html.slim
.small-12.columns.end
  div
    .left-side
      .numbered-circle
        | 2
    .right-side
      h5
        | 建议通话时间及日期

  br

  = render "calls/datetime_picker", today: @today, available_times: @available_times

app/views/experts/_expert_brief_horizontal.html.slim
.expert-brief-blurb-holder
  .left-side
    = image_tag expert.picture.url(:thumb), class: "profile-circle", width: 50
  .right-side
    b
      = expert.name
    .subtitle-holder
      h6
        small.subtitle
          i.fa.fa-graduation-cap
          = " #{expert.list_education}"

      h6
        small.subtitle
          i.fa.fa-map-pin
          = " #{expert.location}"

      h6
        small.subtitle
          i.fa.fa-rmb
          = " #{expert.rate_per_minute}/分钟"

app/views/experts/_expert_brief_vertical.html.slim
.expert-brief-blurb-holder
  div
    = image_tag expert.picture.url(:thumb), class: "profile-circle", width: 100
  div
    b
      = expert.name
    .subtitle-holder
      h6
        small.subtitle
          i.fa.fa-graduation-cap
          = " #{expert.list_education}"

      h6
        small.subtitle
          i.fa.fa-map-pin
          = " #{expert.location}"

      h6
        small.subtitle
          i.fa.fa-rmb
          = " #{expert.rate_per_minute}/分钟"

app/views/experts/_list.html.slim
.expert-list-holder
  .row
    .small-12.medium-3.column.profile-circle-holder
      img.profile-circle src="#{expert.picture.url(:medium)}"
      h4.expert-name
        b
          = expert.name

    .small-12.medium-6.columns
      h5.expert-title
        b
          = expert.title

      .subtitle-holder
        h6
          small.subtitle
            i.fa.fa-graduation-cap
            = " #{expert.list_education}"

        h6
          small.subtitle
            i.fa.fa-map-pin
            = " #{expert.location}"

        - if expert.domestic
          span.label.success
            | 国内

        .expert-details-holder
          div
            .left-side
              .inline-title
                | 现在就职：
            .right-side
              = expert.current_work

          div
            .left-side
              .inline-title
                | 曾经就职：
            .right-side
              = expert.past_work
            
          div
            .left-side
              .inline-title
                | 专长领域：
            .right-side
              = expert.description

          div
            .left-side
              .inline-title
                | 交谈语言：
            .right-side
              = expert.languages

    .small-12.medium-3.column.end.far-right-column
      .hide-for-small-only
        = "每分钟收费：¥#{expert.rate_per_minute}"
        br
      br
      - unless user_signed_in? && current_user == expert
        a.button.primary.expanded href="#{book_expert_path(expert)}"
          | 通话申请
      .show-for-small-only
        = "每分钟收费：¥#{expert.rate_per_minute}"

      = render "experts/read_only_expert_rating", expert: expert

  br
  hr
  br

app/views/experts/_read_only_expert_rating.html.slim
.raty-div.readonly data-rating="#{expert.avg_rating_as_expert}" ng-controller="RatingsCtrl"

.subtitle-holder
  h6
    - if expert.num_comments_from_users > 0
      small.subtitle-linkable data-toggle="commentsFromUsers#{expert.id}"
        i.fa.fa-comments
        = " #{expert.num_comments_from_users}个点评"

      = render "calls/comments_from_users_modal", expert: expert, calls_with_user_reviews: expert.calls_as_expert.reviewed_by_user

    - else
      small.subtitle
        i.fa.fa-comments
        = " #{expert.num_comments_from_users}个点评"

app/views/experts/_stripe_checkout.html.erb
<div class="stripe-holder" data-signed-in="<%= user_signed_in? %>">
  <script src="https://checkout.stripe.com/checkout.js"></script>

  <button id="customButton" class="button">立即申请通话</button>
</div>


<script>
  var handler = StripeCheckout.configure({
    key: "<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>",
    image: "https://s3-us-west-2.amazonaws.com/wokaiqiao/general/square-logo.png",
    locale: "zh",
    token: function(token) {
      var callForm = $(".new_call")
      var isUserSignedIn = $(".book-expert-holder").data("user-signed-in")

      if (!isUserSignedIn) {
        var name = $("#user_name").val()
        var email = $("#user_email").val()
        var password = $("#user_password").val()

        var nameInput = $("<input>")
                       .attr("type", "hidden")
                       .attr("name", "user_name").val(name);

        var emailInput = $("<input>")
                         .attr("type", "hidden")
                         .attr("name", "user_email").val(email);

        var passwordInput = $("<input>")
                           .attr("type", "hidden")
                           .attr("name", "user_password").val(password);

        callForm.append($(nameInput));
        callForm.append($(emailInput));
        callForm.append($(passwordInput));
      }

      var stripeTokenInput = $("<input>")
                             .attr("type", "hidden")
                             .attr("name", "stripe_token").val(token.id);

      callForm.append($(stripeTokenInput));
      callForm.submit()
    }
  });

  $('#customButton').on('click', function(e) {
    e.preventDefault();

    if (validateSignUp()) {
      var email = "<%= current_user.email if user_signed_in? %>"
      if (email == "") {
        email = $("#user_email").val()
      }

      var estimatedDurationInMin = $("#call_est_duration_in_min").val()
      var amount = $("#call_est_duration_in_min").val()
      var ratePerMin = parseInt("<%= expert.rate_per_minute %>")

      // Open Checkout with further options
      handler.open({
        name: '我开窍',
        description: "<%= expert.name %>通话" + estimatedDurationInMin + "分钟",
        currency: "<%= StripeTask::CURRENCY %>",
        amount: estimatedDurationInMin * ratePerMin * 100,
        // alipay: true,
        // "alipay-reusable": true,
        email: email,
        locale: "zh"
      });
    }
  });

  // Close Checkout on page navigation
  $(window).on('popstate', function() {
    handler.close();
  });

  function validateSignUp() {
    var signedIn = $(".stripe-holder").data("signed-in");

    if (signedIn) {
      return true
    }

    $(".error-box").addClass("hide")
    var passValidation = true

    var name = $("#user_name").val()
    var email = $("#user_email").val()
    var password = $("#user_password").val()
    var agreeToPolicies = $("#user_agreed_to_policies").is(':checked')

    if (name == "") {
      $(".name-error").removeClass("hide")
      passValidation = false
    }

    if (email == "") {
      $(".email-missing-error").removeClass("hide")
      passValidation = false
    } else if (!validateEmail(email)) {
      $(".not-proper-email-error").removeClass("hide")
      passValidation = false
    }

    if (password == "") {
      $(".password-missing-error").removeClass("hide")
      passValidation = false
    } else if (password.length < 8) {
      $(".password-length-error").removeClass("hide")
      passValidation = false
    }

    if (!agreeToPolicies) {
      $(".agreed-to-policies-missing-error").removeClass("hide")
      passValidation = false
    }
    
    return passValidation
  }

  function validateEmail(email) {
    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
  }
</script>

app/views/experts/book.html.slim
.page-banner-holder
  .row
    .small-12.columns
      h3
        | 通话申请

.book-expert-holder data-user-signed-in="#{user_signed_in?}"
  .row
    .small-12.large-10.large-offset-1.columns
      .row
        .small-12.medium-8.columns
          .show-for-small-only
            br
            = render "expert_brief_vertical", expert: @expert
            br

          = simple_form_for @call do |f|
            = f.input :expert_id, as: :hidden, input_html: { value: @expert.id }

            .row
              = render "book_section_one", expert: @expert, f: f
            .row
              = render "book_section_two", expert: @expert, f: f
            .row
              = render "book_section_three"

            - if user_signed_in?

              - if current_user.has_free_calls_remaining_to_book?

                = f.input :free, as: :hidden, input_html: { value: true }

                .disclaimer-text
                  p
                    | 你有免费通话的折扣代码，不需要付费。谢谢使用我开窍平台。
                    
              = f.submit "立即申请通话", class: "button"

            - else

              br

              .row
                = render "book_section_four", user: @user, f: f

        .medium-4.columns.hide-for-small-only
          = render "expert_brief_horizontal", expert: @expert

app/views/experts/index.html.slim
.page-banner-holder
  .row
    .small-12.columns
      h3
        | 找专家

.row
  .small-12.columns
    ul.vertical.large-horizontal.menu.menu-centered
      li class="#{'current' if params[:t].nil?}"
        = link_to "全部", experts_path(s: params[:s])

      - @tags.each do |tag|
        li class="#{'current' if params[:t] == tag.id.to_s}"
          a href="#{experts_path(t: tag.id, s: params[:s])}"
            = tag.name

    br

  .small-12.columns
    .pagination-holder
      = paginate @experts

  .small-12.medium-10.medium-offset-1.large-8.large-offset-2.column
    br
    .sort-holder
      | 排序: 
      a href="#{experts_path(t: params[:t], s: User::DOMESTIC)}"
        | 国内先
      | ，
      a href="#{experts_path(t: params[:t], s: User::PRICE_DOWN)}"
        | 收费最高
      | ，
      a href="#{experts_path(t: params[:t], s: User::PRICE_UP)}"
        | 收费最低
      | ，
      a href="#{experts_path(t: params[:t], s: User::MOST_COMMENTS)}"
        | 点评最多
      | ，
      a href="#{experts_path(t: params[:t], s: User::HIGHEST_RATING)}"
        | 评分最高
    hr
    br
    - @experts.each_with_index do |expert, i|
      = render "experts/list", expert: expert, i: i, max: @experts.count

  .small-12.columns
    .pagination-holder
      = paginate @experts